# Generated by Django 3.1.7 on 2021-03-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=200, verbose_name='название статьи')),
                ('article_text', models.TextField(default='', verbose_name='текст статьи')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('author_name', models.CharField(default='', max_length=55, verbose_name='имя автора')),
                ('article_image', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.TextField(verbose_name='текст комментария')),
                ('comment_pub_date', models.DateTimeField(verbose_name='дата публикации комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
