# Generated by Django 3.1.7 on 2021-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_comment_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='1', max_length=50, verbose_name='имя автора'),
        ),
    ]
