# Generated by Django 3.1.7 on 2021-03-23 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210322_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата публикации'),
            preserve_default=False,
        ),
    ]
